WebsiteBanHang/WebsiteBanHang/Areas/Admin/Controllers/BaiVietsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.CSDL;

namespace WebsiteBanHang.Areas.Admin.Controllers
{
    public class BaiVietsController : Controller
    {
        private QLTP3Entities2 db = new QLTP3Entities2();

        // GET: Admin/BaiViets
        string LayMaBV()
        {
            var maMax = db.BaiViets.ToList().Select(n => n.MaBV).Max();
            int maBV = int.Parse(maMax.Substring(2)) + 1;
            string BV = String.Concat("0", maBV.ToString());
            return "BV" + BV.Substring(maBV.ToString().Length - 1);
        }
        public ActionResult Index()
        {
            if (Session["MaNV"] == null)
            {
                return RedirectToAction("LoiPhanQuyen", "Home");
            }
            else
            {
                var baiViets = db.BaiViets.Include(b => b.NhanVien);
                return View(baiViets.ToList());
            }    
                
        }

        // GET: Admin/BaiViets/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiViet baiViet = db.BaiViets.Find(id);
            if (baiViet == null)
            {
                return HttpNotFound();
            }
            return View(baiViet);
        }

        // GET: Admin/BaiViets/Create
        public ActionResult Create()
        {
            ViewBag.MaBV = LayMaBV();
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan");
            return View();
        }

        // POST: Admin/BaiViets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaBV,TenBV,NoiDung,HinhDD,NgayDang,MaNV")] BaiViet baiViet)
        {
            if (ModelState.IsValid)
            {
                db.BaiViets.Add(baiViet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan", baiViet.MaNV);
            return View(baiViet);
        }

        // GET: Admin/BaiViets/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiViet baiViet = db.BaiViets.Find(id);
            if (baiViet == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan", baiViet.MaNV);
            return View(baiViet);
        }

        // POST: Admin/BaiViets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaBV,TenBV,NoiDung,HinhDD,NgayDang,MaNV")] BaiViet baiViet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(baiViet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan", baiViet.MaNV);
            return View(baiViet);
        }

        // GET: Admin/BaiViets/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiViet baiViet = db.BaiViets.Find(id);
            if (baiViet == null)
            {
                return HttpNotFound();
            }
            return View(baiViet);
        }

        // POST: Admin/BaiViets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BaiViet baiViet = db.BaiViets.Find(id);
            db.BaiViets.Remove(baiViet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

   

       [HttpGet]
        public ActionResult TimKiemNC(string MaBV = "", string MaNV = "", string NgayDang = "", string TenBV = "", string HinhDD = "", string NoiDung = "")
        {
            if (Session["MaNV"] == null)
            {
                return RedirectToAction("DangNhapNV", "Home");
            }
            else
            {
                ViewBag.MaBV = MaBV;
                ViewBag.NgayDang = NgayDang;
                ViewBag.TenBV = TenBV;
                ViewBag.HinhDD = HinhDD;
                ViewBag.NoiDung = NoiDung;
                ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "MaNV");
                var baiViets = db.BaiViets.SqlQuery("BaiViet_TimKiemNC'" + MaBV + "','" + MaNV + "','" + NgayDang + "','" + TenBV + "','" + HinhDD + "','" + NoiDung + "'");
                if (baiViets.Count() == 0)
                    ViewBag.TB = "Không có thông tin tìm kiếm.";
                return View(baiViets.ToList());
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsiteBanHang/WebsiteBanHang/Controllers/BaiVietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.CSDL;
using WebsiteBanHang.Models;
using PagedList;

namespace WebsiteBanHang.Controllers
{
    public class BaiVietController : Controller
    {
        QLTP3Entities2 objQLTPEntities = new QLTP3Entities2();
        QLTP3Entities2 db = new QLTP3Entities2();

        // GET: BaiViet
        public ActionResult Index(int? page)
        {
            var lstSP = db.BaiViets;
         
            int PageSize = 9;
            int PageNumber = (page ?? 1);

            return View(lstSP.OrderBy(n => n.MaBV).ToPagedList(PageNumber, PageSize));
        }

        

        public ActionResult ChiTietBaiViet(String MaBV)
        {
            HomeModel objHomeModel2 = new HomeModel();       
            objHomeModel2.ListBaiViet = objQLTPEntities.BaiViets.Where(n => n.MaBV == MaBV).ToList();
            objHomeModel2.ListFullBaiViet = objQLTPEntities.BaiViets.ToList();
            objHomeModel2.ListNhaCungCap = objQLTPEntities.NhaCungCaps.ToList();
            objHomeModel2.ListDanhMuc = objQLTPEntities.DanhMucs.ToList();
           
            return View(objHomeModel2);
        }

    }
}

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/BaiViets/Create.cshtml
@model WebsiteBanHang.CSDL.BaiViet

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content-wrapper">
    <br />

    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>BaiViet</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaBV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.MaBV" disabled readonly class="form-control" />
                @*@Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.MaBV, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenBV, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenBV, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenBV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhDD, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HinhDD, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HinhDD, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayDang, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayDang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayDang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNV, "MaNV", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>


</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/BaiViets/Delete.cshtml
@model WebsiteBanHang.CSDL.BaiViet

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <br />
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>BaiViet</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TenBV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TenBV)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NoiDung)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NoiDung)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HinhDD)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HinhDD)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NgayDang)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayDang)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NhanVien.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NhanVien.TaiKhoan)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>


</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/BaiViets/Details.cshtml
@model WebsiteBanHang.CSDL.BaiViet

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <br />
    <h2>Details</h2>

    <div>
        <h4>BaiViet</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TenBV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TenBV)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NoiDung)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NoiDung)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HinhDD)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HinhDD)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NgayDang)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayDang)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NhanVien.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NhanVien.TaiKhoan)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.MaBV }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/BaiViets/Edit.cshtml
@model WebsiteBanHang.CSDL.BaiViet

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <br />
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>BaiViet</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaBV)

            <div class="form-group">
                @Html.LabelFor(model => model.TenBV, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenBV, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenBV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HinhDD, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HinhDD, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HinhDD, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayDang, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayDang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayDang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNV, "MaNV", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    s
</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/BaiViets/Index.cshtml
@model IEnumerable<WebsiteBanHang.CSDL.BaiViet>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content-wrapper">
    <br />
    <table class="table table-bordered" style="width:100%" id="example">
        <thead class="thead-dark">
            <tr>
                <th>Mã bài viết</th>
                <th>Tên bài viết</th>
                <th>Nội dung</th>
                <th>Hình DD</th>
                <th>Ngày đăng</th>
                <th>Mã nhân viên</th>
            </tr>

           

        </thead>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaBV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenBV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoiDung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HinhDD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayDang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaNV)
        </td>

      

    </tr>
        }

    </table>

</div>

@section scripts {
    <script type="text/javascript">
            $(document).ready(function () {
                $("#example").dataTable({
                    "columns": [
                        { 'data': 'MaBV' },
                        { 'data': 'TenBV' },
                        { 'data': 'NoiDung' },
                        { 'data': 'HinhDD' },
                        { 'data': 'NgayDang' },
                        { 'data': 'MaNV)' },     
                    ],
                    "dom": 'Bfrtip',
                    "buttons": [
                        'copy', 'csv', 'excel', 'pdf', 'print'
                    ]
                })
            })
    </script>
}

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/BaiViets/TimKiemNC.cshtml
@model List<WebsiteBanHang.CSDL.BaiViet>

@{
    ViewBag.Title = "TimKiemNC";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaBV", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<div class="content-wrapper">
    <br />
    <div>
        @using (Html.BeginForm("TimKiemNC", "BaiViets", FormMethod.Get))
        {
            @Html.AntiForgeryToken()
        <table class="table1" align="center">
            <tr>
                <td>
                    <div>Mã bài viết</div>
                </td>
                <td>
                    <input type="text" name="MaBV" value="@ViewBag.MaBV" />
                </td>

            </tr>
            <tr>
                <td>Tên bài viết</td>
                <td>
                    <input type="text" name="TenBV" value="@ViewBag.TenBV" />
                </td>

            </tr>

            <tr>
                <td>Nội dung</td>
                <td>
                    <input type="text" name="NoiDung" value="@ViewBag.NoiDung" />
                </td>
            </tr>
            <tr>
                <td>Hình đại diện</td>
                <td>
                    <input type="text" name="HinhDD" value="@ViewBag.HinhDD" />
                </td>
            </tr>

            <tr>
                <td>Ngày đăng</td>
                <td>
                    <input type="text" name="NgayDang" value="@ViewBag.NgayDang" />
                </td>
            </tr>

            <tr>
                <td>Mã nhân viên</td>
                <td>
                    @Html.DropDownList("MaNV", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
                </td>
            </tr>
            <tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" />
                    <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" onclick="location.href='@Url.Action("TimKiemNC", "BaiViets/TimKiemNC")'" />

                </td>
            </tr>
        </table>
        }
    </div>

    <br />

    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
             {
         grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
        grid.Column("MaBV","Mã bài viết"), //the model fields to display
        grid.Column("TenBV","Tên bài viết"),
        grid.Column("NgayDang","Ngày đăng",format:@<text> @item.NgayDang.ToString("dd/MM/yyyy")</text>),

grid.Column("NoiDung","Nội dung"),
grid.Column("HinhDD","HinhDD"),
grid.Column("NhanVien.MaNV","Nhân viên"),
grid.Column("Chức năng", format: @<text>
            <a href="@Url.Action("Edit",
                                    new { id = item.MaBV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="~/content/images/icons/edit.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Details",
                                    new { id = item.MaBV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="~/content/images/icons/details.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Delete",
                                    new { id = item.MaBV})" class="edit-btn">
                <abbr title="Xóa dữ liệu">
                    <img src="~/content/images/icons/delete.png" width="20" height="20" />
                </abbr>
            </a>
</text>),

}
)
    </div>


</div>