WebsiteBanHang/WebsiteBanHang/Controllers/BaiVietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.CSDL;
using WebsiteBanHang.Models;
using PagedList;

namespace WebsiteBanHang.Controllers
{
    public class BaiVietController : Controller
    {
        QLTP3Entities2 objQLTPEntities = new QLTP3Entities2();
        QLTP3Entities2 db = new QLTP3Entities2();

        // GET: BaiViet
        public ActionResult Index(int? page)
        {
            var lstSP = db.BaiViets;
         
            int PageSize = 9;
            int PageNumber = (page ?? 1);

            return View(lstSP.OrderBy(n => n.MaBV).ToPagedList(PageNumber, PageSize));
        }

        

        public ActionResult ChiTietBaiViet(String MaBV)
        {
            HomeModel objHomeModel2 = new HomeModel();       
            objHomeModel2.ListBaiViet = objQLTPEntities.BaiViets.Where(n => n.MaBV == MaBV).ToList();
            objHomeModel2.ListFullBaiViet = objQLTPEntities.BaiViets.ToList();
            objHomeModel2.ListNhaCungCap = objQLTPEntities.NhaCungCaps.ToList();
            objHomeModel2.ListDanhMuc = objQLTPEntities.DanhMucs.ToList();
           
            return View(objHomeModel2);
        }

    }
}

WebsiteBanHang/WebsiteBanHang/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.CSDL;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    public class GioHangController : Controller
    {
        QLTP3Entities2 objQLTPEntities = new QLTP3Entities2();

        public ActionResult Index()
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            return View(giohang);
        }

        public ActionResult NhapThongTin()
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            return View(giohang);
        }

        public RedirectToRouteResult ThemVaoGio(String MaSP)
        {
            if (Session["giohang"] == null) // Nếu giỏ hàng chưa được khởi tạo
            {
                Session["giohang"] = new List<CartItem>();  // Khởi tạo Session["giohang"] là 1 List<CartItem>
            }

            List<CartItem> giohang = Session["giohang"] as List<CartItem>;  // Gán qua biến giohang dễ code

            // Kiểm tra xem sản phẩm khách đang chọn đã có trong giỏ hàng chưa

            if (giohang.FirstOrDefault(m => m.MaSP == MaSP) == null) // ko co sp nay trong gio hang
            {
                SanPham sp = objQLTPEntities.SanPhams.Find(MaSP);  // tim sp theo MaSP

                CartItem newItem = new CartItem()
                {
                    MaSP = MaSP,
                    TenSP = sp.TenSP,
                    SoLuong = 1,
                    HinhDD = sp.HinhDD,
                    DonGia = (float)sp.GiaBan

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                CartItem cardItem = giohang.FirstOrDefault(m => m.MaSP == MaSP);
                cardItem.SoLuong++;
            }

            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public RedirectToRouteResult ThemVaoGioCT(String MaSP, int SoLuong)
        {
            if (Session["giohang"] == null) // Nếu giỏ hàng chưa được khởi tạo
            {
                Session["giohang"] = new List<CartItem>();  // Khởi tạo Session["giohang"] là 1 List<CartItem>
            }

            List<CartItem> giohang = Session["giohang"] as List<CartItem>;  // Gán qua biến giohang dễ code

            // Kiểm tra xem sản phẩm khách đang chọn đã có trong giỏ hàng chưa

            if (giohang.FirstOrDefault(m => m.MaSP == MaSP) == null) // ko co sp nay trong gio hang
            {
                SanPham sp = objQLTPEntities.SanPhams.Find(MaSP);  // tim sp theo MaSP

                CartItem newItem = new CartItem()
                {
                    MaSP = MaSP,
                    TenSP = sp.TenSP,
                    SoLuong = SoLuong,
                    HinhDD = sp.HinhDD,
                    DonGia = (float)sp.GiaBan

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                CartItem cardItem = giohang.FirstOrDefault(m => m.MaSP == MaSP);
                cardItem.SoLuong = cardItem.SoLuong + SoLuong;
            }

            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            return RedirectToAction("Detail", "Product", new { MaSP = MaSP });
        }

        public RedirectToRouteResult ThemVaoGioDMLst(String MaSP, String MaDM)
        {
            if (Session["giohang"] == null) // Nếu giỏ hàng chưa được khởi tạo
            {
                Session["giohang"] = new List<CartItem>();  // Khởi tạo Session["giohang"] là 1 List<CartItem>
            }

            List<CartItem> giohang = Session["giohang"] as List<CartItem>;  // Gán qua biến giohang dễ code

            // Kiểm tra xem sản phẩm khách đang chọn đã có trong giỏ hàng chưa

            if (giohang.FirstOrDefault(m => m.MaSP == MaSP) == null) // ko co sp nay trong gio hang
            {
                SanPham sp = objQLTPEntities.SanPhams.Find(MaSP);  // tim sp theo MaSP

                CartItem newItem = new CartItem()
                {
                    MaSP = MaSP,
                    TenSP = sp.TenSP,
                    SoLuong = 1,
                    HinhDD = sp.HinhDD,
                    DonGia = (float)sp.GiaBan

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                CartItem cardItem = giohang.FirstOrDefault(m => m.MaSP == MaSP);
                cardItem.SoLuong++;
            }

            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            return RedirectToAction("SanPhamDanhMuc", "DanhMuc", new { MaDM = MaDM });
        }

        public RedirectToRouteResult ThemVaoGioDMGr(String MaSP, String MaDM)
        {
            if (Session["giohang"] == null) // Nếu giỏ hàng chưa được khởi tạo
            {
                Session["giohang"] = new List<CartItem>();  // Khởi tạo Session["giohang"] là 1 List<CartItem>
            }

            List<CartItem> giohang = Session["giohang"] as List<CartItem>;  // Gán qua biến giohang dễ code

            // Kiểm tra xem sản phẩm khách đang chọn đã có trong giỏ hàng chưa

            if (giohang.FirstOrDefault(m => m.MaSP == MaSP) == null) // ko co sp nay trong gio hang
            {
                SanPham sp = objQLTPEntities.SanPhams.Find(MaSP);  // tim sp theo MaSP

                CartItem newItem = new CartItem()
                {
                    MaSP = MaSP,
                    TenSP = sp.TenSP,
                    SoLuong = 1,
                    HinhDD = sp.HinhDD,
                    DonGia = (float)sp.GiaBan

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                CartItem cardItem = giohang.FirstOrDefault(m => m.MaSP == MaSP);
                cardItem.SoLuong++;
            }

            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            return RedirectToAction("SanPhamDanhMuc2", "DanhMuc", new { MaDM = MaDM });
        }

        public RedirectToRouteResult SuaSoLuong(String MaSP, int soluongmoi)
        {
            // tìm carditem muon sua
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem itemSua = giohang.FirstOrDefault(m => m.MaSP == MaSP);
            if (itemSua != null)
            {
                itemSua.SoLuong = soluongmoi;
            }
            return RedirectToAction("Index");

        }

        public RedirectToRouteResult XoaKhoiGio(String MaSP)
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem itemXoa = giohang.FirstOrDefault(m => m.MaSP == MaSP);
            if (itemXoa != null)
            {
                giohang.Remove(itemXoa);
            }
            return RedirectToAction("Index");
        }

    }
}

WebsiteBanHang/WebsiteBanHang/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.CSDL;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    public class ProductController : Controller
    {

        QLTP3Entities2 objQLTPEntities = new QLTP3Entities2();

        // Xem thoong tin cu the cua mot doi tuong
        // GET: Product
        public ActionResult Detail(String MaSP)
        {
            HomeModel objHomeModel = new HomeModel();
            objHomeModel.ListNhaCungCap = objQLTPEntities.NhaCungCaps.ToList();
            objHomeModel.ListDanhMuc = objQLTPEntities.DanhMucs.ToList();
            objHomeModel.ListBaiViet = objQLTPEntities.BaiViets.ToList();
            objHomeModel.ListSanPham = objQLTPEntities.SanPhams.Where(n => n.MaSP == MaSP).ToList();
            return View(objHomeModel);

        }


      
    }
}

WebsiteBanHang/WebsiteBanHang/Views/Product/Detail.cshtml
@model WebsiteBanHang.Models.HomeModel


@{
    ViewBag.Title = "Detail";
}




<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">

    @foreach (var item in Model.ListSanPham)
    {
        <div class="container">
            <!-- ============================ ITEM DETAIL ======================== -->

            <div class="row">
                <aside class="col-md-6">
                    <div class="card">
                        <article class="gallery-wrap">
                            <div class="img-big-wrap">
                                <div> <a href="#"><img src="~/Content/images/items/@item.HinhDD"></a></div>
                            </div> <!-- slider-product.// -->
                            <div class="thumbs-wrap">
                                <a href="#" class="item-thumb"> <img src="~/Content/images/items/@item.HinhDD"></a>
                              
                            </div> <!-- slider-nav.// -->
                        </article> <!-- gallery-wrap .end// -->
                    </div> <!-- card.// -->
                </aside>
                <main class="col-md-6">
                    <article class="product-info-aside">

                        <h2 class="title mt-3">@item.TenSP </h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width:80%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>

                        </div> <!-- rating-wrap.// -->

                        <div class="mb-3">
                            <var class="price h4">@item.GiaBan</var>
                            <span class="text-muted">đ</span>
                        </div> <!-- price-detail-wrap .// -->


                        @foreach (var itemncc in Model.ListNhaCungCap.Where(n => n.MaNCC == item.MaNCC))
                        {
                            <dl class="row">
                                <dt class="col-sm-3">Tên nhà cung cấp</dt>
                                <dd class="col-sm-9"><a href="#">@itemncc.TenNCC</a></dd>

                                <dt class="col-sm-3">Số điện thoại</dt>
                                <dd class="col-sm-9">@itemncc.SoDT</dd>


                            </dl>
                        }


                    <div class="form-row  mt-4">
                        <div class="form-group col-md flex-grow-0">

                            @using (Html.BeginForm("ThemVaoGioCT", "GioHang", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()

                                   @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                     @Html.HiddenFor(m => m.MaSP)
                               
                                 

                           
                                <div class="form-group">
                                    @Html.TextBoxFor(m => m.SoLuong, "1", new { @class = "form-control" })
                                </div>

                                <div class="form-group">
                                    <input type="submit" name="submit" class="btn btn-success btn-block" value="Thêm vào giỏ hàng" />
                                </div>
                            }


                        </div> <!-- col.// -->
                            </div> <!-- row.// -->

                    </article> <!-- product-info-aside .// -->
                </main> <!-- col.// -->
            </div> <!-- row.// -->
            <!-- ================ ITEM DETAIL END .// ================= -->


        </div> <!-- container .//  -->
    }

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y bg">
    <div class="container">
        <div class="row">
            @foreach (var item in Model.ListSanPham)
            {
                <div class="col-md-8">
                    <h5 class="title-description">Thông tin sản phẩm</h5>
                    <p> @item.MoTaCT</p>
                    <h5 class="title-description">Đánh giá sản phẩm</h5>
                    <div>
                        <img src="~/Content/images/posts/danhgia.PNG" />
                    </div>
                    <br />
                    <br />
                    <div class="row">
                        <div class="col-xl-6">
                            <img src="~/Content/images/banners/k1.png" />
                        </div>

                        <div class="col-xl-6">
                            <img src="~/Content/images/banners/k2.png" />
                        </div>
                    </div>
                </div> <!-- col.// -->
            }

            <aside class="col-md-4">

                <div class="box">

                    <h5 class="title-description">Bài Viết Liên Quan</h5>


                    @foreach (var item in Model.ListBaiViet.Take(3))
                    {
                        <article class="media mb-3">
                            <a href="#"><img class="img-sm mr-3" src="~/Content/images/posts/@item.HinhDD"></a>
                            <div class="media-body">
                                <h6 class="mt-0"><a href="#">@item.TenBV</a></h6>
                                <p class="mb-2">@item.NgayDang </p>
                                <a href="@Url.Action("ChiTietBaiViet", "BaiViet", new { MaBV = item.MaBV})"
                                   class="btn btn-light">Xem ngay! </a>
                            </div>
                        </article>
                    }


                </div> <!-- box.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->