WebsiteBanHang/WebsiteBanHang/Areas/Admin/Controllers/HoaDonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.CSDL;

namespace WebsiteBanHang.Areas.Admin.Controllers
{
    public class HoaDonsController : Controller
    {
        private QLTP3Entities2 db = new QLTP3Entities2();

        string LayMaHD()
        {
            var maMax = db.HoaDons.ToList().Select(n => n.MaHD).Max();
            int MaHD = int.Parse(maMax.Substring(2)) + 1;
            string HD = String.Concat("00", MaHD.ToString());
            return "HD" + HD.Substring(MaHD.ToString().Length - 1);
        }
        // GET: Admin/HoaDons
        public ActionResult Index()
        {
            var hoaDons = db.HoaDons.Include(h => h.KhachHang).Include(h => h.NhanVien).Include(h => h.TrangThai);
            return View(hoaDons.ToList());
        }

        // GET: Admin/HoaDons/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // GET: Admin/HoaDons/Create
        public ActionResult Create()
        {
            ViewBag.MaHD = LayMaHD();
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TaiKhoan");
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan");
            ViewBag.MaTT = new SelectList(db.TrangThais, "MaTT", "TenTT");
            return View();
        }

        // POST: Admin/HoaDons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHD,NgayDat,NgayGiao,SoDT,DiaChi,GhiChu,MaTT,MaNV,MaKH,ThanhToan")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                db.HoaDons.Add(hoaDon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TaiKhoan", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan", hoaDon.MaNV);
            ViewBag.MaTT = new SelectList(db.TrangThais, "MaTT", "TenTT", hoaDon.MaTT);
            return View(hoaDon);
        }

        // GET: Admin/HoaDons/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TaiKhoan", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan", hoaDon.MaNV);
            ViewBag.MaTT = new SelectList(db.TrangThais, "MaTT", "TenTT", hoaDon.MaTT);
            return View(hoaDon);
        }

        // POST: Admin/HoaDons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHD,NgayDat,NgayGiao,SoDT,DiaChi,GhiChu,MaTT,MaNV,MaKH,ThanhToan")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hoaDon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TaiKhoan", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TaiKhoan", hoaDon.MaNV);
            ViewBag.MaTT = new SelectList(db.TrangThais, "MaTT", "TenTT", hoaDon.MaTT);
            return View(hoaDon);
        }

        // GET: Admin/HoaDons/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // POST: Admin/HoaDons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HoaDon hoaDon = db.HoaDons.Find(id);
            db.HoaDons.Remove(hoaDon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult TimKiemNC(string MaHD = "", string NgayDat = "", string NgayGiao = "", string DiaChi = "",   string MaTT = "", string MaNV = "", string MaKH = "")
        {
            if (Session["MaNV"] == null)
            {
                return RedirectToAction("DangNhapNV", "Home");
            }
            else
            {
                ViewBag.MaHD = MaHD;
                ViewBag.NgayDat = NgayDat;
                ViewBag.NgayGiao = NgayGiao;
                ViewBag.DiaChi = DiaChi;                
                ViewBag.MaTT = new SelectList(db.TrangThais, "MaTT", "TenTT");
                ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "MaNV");
                ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "MaKH");
                var hoaDons = db.HoaDons.SqlQuery("HoaDon_TimKiemNC'" + MaHD + "','" + NgayDat + "','" + NgayGiao + "','" + DiaChi + "','" + MaTT + "','" + MaNV + "','" + MaKH + "'");
                if (hoaDons.Count() == 0)
                    ViewBag.TB = "Không có thông tin tìm kiếm.";
                return View(hoaDons.ToList());
            }    

            
        }


        [HttpGet]
        public ActionResult XuatTest()
        {
            return View();
        }


        public ActionResult ChuaDuyet()
        {
            var lstDSDHCD = db.HoaDons.Where(n => n.MaTT == "TT1");
            return View(lstDSDHCD);
        }

        public ActionResult ChuaGiao()
        {
            var lstDSDHCG = db.HoaDons.Where(n => n.MaTT == "TT3");
            return View(lstDSDHCG);
        }

        public ActionResult DaGiaoDaThanhToan()
        {
            var lstDSDHDHT = db.HoaDons.Where(n => n.MaTT == "TT4");
            return View(lstDSDHDHT);
        }
       


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/HoaDons/Create.cshtml
@model WebsiteBanHang.CSDL.HoaDon

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>HoaDon</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaHD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.MaHD" disabled readonly class="form-control" />
                @*@Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.MaHD, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayDat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayGiao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoDT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaTT, "MaTT", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaTT", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaTT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNV, "MaNV", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaKH, "MaKH", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaKH", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>


</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/HoaDons/Delete.cshtml
@model WebsiteBanHang.CSDL.HoaDon

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <br />

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>HoaDon</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NgayDat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayDat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NgayGiao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayGiao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SoDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SoDT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GhiChu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GhiChu)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.KhachHang.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KhachHang.TaiKhoan)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NhanVien.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NhanVien.TaiKhoan)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TrangThai.TenTT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TrangThai.TenTT)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>


</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/HoaDons/Details.cshtml
@model WebsiteBanHang.CSDL.HoaDon

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <br />
    <div>
        <h4>HoaDon</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NgayDat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayDat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NgayGiao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgayGiao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SoDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SoDT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GhiChu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GhiChu)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.KhachHang.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KhachHang.TaiKhoan)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NhanVien.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NhanVien.TaiKhoan)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TrangThai.TenTT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TrangThai.TenTT)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.MaHD }) |
        @Html.ActionLink("Back to List", "Index")
    </p>


</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/HoaDons/Edit.cshtml
@model WebsiteBanHang.CSDL.HoaDon

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
   
}

<div class="content-wrapper">

    <br/>
    <h2>Chỉnh sửa</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>HoaDon</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaHD)

            <div class="form-group">
                @Html.LabelFor(model => model.NgayDat, "Thời gian đặt hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayGiao, "Thời gian giao hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoDT, "SĐT giao hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, "Địa chỉ giao hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.MaKH, "Mã khách hàng đặt", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaNV, "Mã nhân viện duyệt", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaTT, "MaTT", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaTT", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaTT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu lại" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Trở lại", "Index")
    </div>


</div>

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/HoaDons/Index.cshtml
@model IEnumerable<WebsiteBanHang.CSDL.HoaDon>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="content-wrapper">
    <br />
    <table class="table table-bordered" style="width:100%" id="example">
        <thead class="thead-dark">
            <tr>
                <th>Mã hóa đơn</th>
                <th>Ngày đặt</th>
                <th>Ngày giao</th>
                <th>Số điện thoại</th>
                <th>Địa chỉ</th>
                <th>Ghi chú</th>
                <th>Mã trạng thái</th>
                <th>Mã nhân viên</th>
                <th>Mã khách hàng</th>
                <th>Thanh toán</th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaHD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayDat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayGiao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiaChi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GhiChu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaTT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaNV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaKH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThanhToan)
        </td>

    </tr>
        }

    </table>

</div>

@section scripts {
    <script type="text/javascript">
$(document).ready(function () {
                $("#example").dataTable({
                    "columns": [
                        { 'data': 'MaHD' },
                        { 'data': 'NgayDat' },
                        { 'data': 'NgayGiao' },
                        { 'data': 'SoDT' },
                        { 'data': 'DiaChi' },
                        { 'data': 'GhiChu' },
                        { 'data': 'MaTT' },
                        { 'data': 'MaNV' },
                        { 'data': 'ThanhToan' },

                        { 'data': 'MaKH' },
                    ],
                    "dom": 'Bfrtip',
                    "buttons": [
                        'copy', 'csv', 'excel', 'pdf', 'print'
                    ]
                })
            })</script>
}

WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/HoaDons/TimKiemNC.cshtml
@model List<WebsiteBanHang.CSDL.HoaDon>
@{
    ViewBag.Title = "TimKiemNC";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaHD", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")

}
<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<div class="content-wrapper">
    <br />
    <body>
        <div>
            @using (Html.BeginForm("TimKiemNC", "HoaDons", FormMethod.Get))
            {
                @Html.AntiForgeryToken()

            <table class="table1" align="center">
                <tr>
                    <td>
                        <div> Mã hóa đơn</div>
                    </td>
                    <td>
                        <input type="text" name="MaHD" value="@ViewBag.MaHD" />
                    </td>
                </tr>
                <tr>
                    <td>Ngày đặt</td>
                    <td>
                        <input type="text" name="NgayDat" value="@ViewBag.NgayDat" />
                    </td>

                </tr>

                <tr>
                    <td>Ngày giao</td>
                    <td>
                        <input type="text" name="NgayGiao" value="@ViewBag.NgayGiao" />
                    </td>
                </tr>
                <tr>
                    <td>Địa chỉ</td>
                    <td>
                        <input type="text" name="DiaChi" value="@ViewBag.DiaChi" />
                    </td>
                </tr>
                <tr>
                    <td>Trạng Thái</td>
                    <td>
                        @Html.DropDownList("MaTT", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
                    </td>
                </tr>
                <tr>
                <tr>
                    <td>Nhân Viên</td>
                    <td>
                        @Html.DropDownList("MaNV", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
                    </td>
                </tr>
                <tr>
                    <td>Khách Hàng</td>
                    <td>
                        @Html.DropDownList("MaKH", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" />
                        <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" onclick="location.href='@Url.Action("TimKiemNC", "HoaDons/TimKiemNC")'" />

                    </td>
                </tr>
            </table>
            }
        </div>
        <div id="gridContent">
            @ViewBag.TB
            @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                footerStyle: "grid-footer",
                fillEmptyRows: true,
                mode: WebGridPagerModes.Numeric,
                alternatingRowStyle: "alternatingRowStyle",
                  columns: new[]  // colums in grid
                 {
             grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaHD","Mã hóa đơn"), //the model fields to display
            grid.Column("NgayDat","Ngày đặt",format:@<text> @item.NgayDat.ToString("dd/MM/yyyy")</text>),
grid.Column("NgayGiao","Ngày giao",format:@<text> @item.NgayGiao.ToString("dd/MM/yyyy")</text>),
grid.Column("SoDT","Số điện thoại"),
grid.Column("DiaChi","Địa chỉ"),
grid.Column("GhiChu","Ghi chú"),
grid.Column("ThanhToan","Thanh toán"),
grid.Column("TrangThai.TenTT","Trạng thái"),
grid.Column("NhanVien.MaNV","Nhân Viên"),
grid.Column("KhachHang.MaKH","Khách Hàng"),

grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit",
                        new { id = item.MaHD})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="~/content/images/icons/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details",
                        new { id = item.MaHD})" class="edit-btn"><abbr title="Xem chi tiết"><img src="~/content/images/icons/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete",
                        new { id = item.MaHD})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <img src="~/content/images/icons/delete.png" width="20" height="20" />
        </abbr>
    </a>
</text>),

}
)
        </div>
    </body>


    </div>
</html>